/**
 * Generate TypeScript modules under src/generated/<env>/<fix>/ from the committed schema XML files.
 */
import fs from 'node:fs';
import path from 'node:path';
import { parseDictionary } from './lib/schema.js';
import { generate } from './lib/generate-ts.js';
import { ENVS, FIXES, SOURCES, resolveRepo } from './lib/sources.js';

const generatedRoot = resolveRepo('src', 'generated');
fs.rmSync(generatedRoot, { recursive: true, force: true });

const banner = '// Generated by scripts/generate.ts — DO NOT EDIT.';
const present = new Set<string>();

for (const s of SOURCES) {
  const xmlPath = resolveRepo(s.localPath);
  if (!fs.existsSync(xmlPath)) {
    console.warn(`skip ${s.env}/${s.fix}: ${s.localPath} not found (run \`pnpm fetch-schemas\`)`);
    continue;
  }
  const dict = parseDictionary(fs.readFileSync(xmlPath, 'utf8'));
  const files = generate(dict);
  const outDir = resolveRepo(s.outDir);
  fs.mkdirSync(outDir, { recursive: true });
  for (const [name, content] of Object.entries(files)) fs.writeFileSync(path.join(outDir, name), content);
  present.add(`${s.env}/${s.fix}`);
  console.log(
    `${s.env}/${s.fix}: ${dict.messages.length} messages, ${dict.components.length} components, ${dict.fields.length} fields — ${dict.version.raw}`,
  );
}

for (const env of ENVS) {
  const lines = [banner, ''];
  for (const fix of FIXES) {
    if (present.has(`${env}/${fix}`)) lines.push(`export * as ${fix} from './${fix}/index.js';`);
  }
  fs.mkdirSync(path.join(generatedRoot, env), { recursive: true });
  fs.writeFileSync(path.join(generatedRoot, env, 'index.ts'), lines.join('\n') + '\n');
}
